# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_basecustomermodel'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='modified',
        ),
        migrations.AddField(
            model_name='organization',
            name='basecustomermodel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customers.BaseCustomerModel'),
            preserve_default=False,
        ),
    ]
