# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_minisite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minisite',
            name='version',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
