# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:53
from __future__ import unicode_literals

from django.db import migrations
import jsoneditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_minisite', '0003_auto_20160629_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minisite',
            name='theme_data',
            field=jsoneditor.fields.JSONSchemaField(blank=True, default=dict, null=True),
        ),
    ]
