# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 10:11
from __future__ import unicode_literals

from django.db import migrations
import jsoneditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_minisite', '0004_auto_20160629_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minisite',
            name='features_data',
            field=jsoneditor.fields.JSONSchemaField(blank=True, default=dict, null=True),
        ),
    ]
