# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_minisite', '0005_auto_20160630_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='minisite',
            name='site_template',
            field=models.CharField(choices=[('merlin', 'merlin-master')], default='merlin-master', max_length=200),
        ),
    ]
