# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 19:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_minisite', '0006_minisite_site_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minisite',
            name='contact_data',
        ),
        migrations.RemoveField(
            model_name='minisite',
            name='features_data',
        ),
        migrations.RemoveField(
            model_name='minisite',
            name='theme_data',
        ),
        migrations.AddField(
            model_name='minisite',
            name='site_content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='minisite',
            name='site_style',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='minisite',
            name='site_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
