# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_minisite', '0007_auto_20160702_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minisite',
            name='site_template',
            field=models.CharField(choices=[('merlin-master', 'merlin-master')], default='merlin-master', max_length=200),
        ),
    ]
