# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_minisite', '0008_auto_20160702_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minisite',
            name='site_template',
            field=models.CharField(choices=[('merlin-master', 'merlin-master'), ('startbootstrap-grayscale', 'startbootstrap-grayscale')], default='merlin-master', max_length=200),
        ),
    ]
